# Generated by Django 5.1.3 on 2024-11-13 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PipeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=50)),
                ("scale_pixel_value_max", models.FloatField(blank=True, null=True)),
                ("crop_left", models.IntegerField(blank=True, null=True)),
                ("crop_right", models.IntegerField(blank=True, null=True)),
                ("crop_top", models.IntegerField(blank=True, null=True)),
                ("crop_bottom", models.IntegerField(blank=True, null=True)),
                ("kernel_size_horizontal", models.IntegerField(blank=True, null=True)),
                ("kernel_size_vertical", models.IntegerField(blank=True, null=True)),
                (
                    "kernel_function_horizontal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "kernel_function_vertical",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pixel_change_threshold", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoreColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_order", models.IntegerField(blank=True, null=True)),
                ("column_width", models.IntegerField(blank=True, null=True)),
                ("pixel_start", models.IntegerField(blank=True, null=True)),
                ("pixel_end", models.IntegerField(blank=True, null=True)),
                ("varve_count", models.IntegerField(blank=True, null=True)),
                (
                    "pipe_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autovarve.piperun",
                    ),
                ),
            ],
        ),
    ]
